server.port: 8080

app.eureka-server: eureka
# not needed because I use eureka client for discovery service
#app:
#  product-service:
#    host: product
#    port: 8080
#  recommendation-service:
#    host: recommendation
#    port: 8080
#  review-service:
#    host: sb3-review
#    port: 8080


spring.cloud.stream.kafka.binder.brokers: kafka

spring.cloud.stream.bindings:
  products-out-0.producer:
    partition-key-expression: headers['partitionKey']
    partition-count: 2
  recommendations-out-0.producer:
    partition-key-expression: headers['partitionKey']
    partition-count: 2
  reviews-out-0.producer:
    partition-key-expression: headers['partitionKey']
    partition-count: 2

management.health.rabbit.enabled: false
spring.cloud.stream.defaultBinder: kafka
spring.kafka.bootstrap-servers: kafka:9092
spring.cloud.stream.kafka.binder.replication-factor: 1